# Spring
spring.application.name=LangChain4j-Spring-Boot
server.port=8082

#langchain4j.open-ai.chat-model.api-key=0916438ff216e4ab5ad2a958f2606791d.sKquJCflU3N6Q2tx
#langchain4j.open-ai.chat-model.base-url=https://open.bigmodel.cn/api/paas/v4
#langchain4j.open-ai.chat-model.model-name=glm-5.1
#langchain4j.open-ai.chat-model.log-requests=true
#langchain4j.open-ai.chat-model.log-responses=true

langchain4j.community.dashscope.chat-model.api-key=${DASHSCOPE_API_KEY}
langchain4j.community.dashscope.chat-model.model-name=qwen-plus
langchain4j.community.dashscope.chat-model.parameters.temperature=0.7
langchain4j.community.dashscope.chat-model.max-tokens=4096