# Spring
spring.application.name=LangChain4j-Spring-Boot
server.port=8082

langchain4j.community.dashscope.chat-model.api-key=${DASHSCOPE_API_KEY}
langchain4j.community.dashscope.chat-model.model-name=qwen-plus
langchain4j.community.dashscope.chat-model.parameters.temperature=0.7
langchain4j.community.dashscope.chat-model.max-tokens=4096