# Spring
spring.application.name=LangChain4j-Spring-Boot
server.port=8082

logging.level.dev.langchain4j=DEBUG

langchain4j.open-ai.chat-model.api-key=demo
langchain4j.open-ai.chat-model.base-url=http://langchain4j.dev/demo/openai/v1
langchain4j.open-ai.chat-model.model-name=gpt-4o-mini
langchain4j.open-ai.chat-model.log-requests=true
langchain4j.open-ai.chat-model.log-responses=true

#langchain4j.open-ai.streaming-chat-model.api-key=${OPENAI_API_KEY}
#langchain4j.open-ai.streaming-chat-model.model-name=gpt-4o-mini
#langchain4j.open-ai.streaming-chat-model.log-requests=true
#langchain4j.open-ai.streaming-chat-model.log-responses=true